name: znn_cli_dart
description: Zenon CLI tool
version: 0.0.4
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dcli: ^3.0.2
  args: ^2.4.2
  znn_sdk_dart:
    git:
      url: https://github.com/alienc0der/znn_sdk_dart.git
      ref: e0b39b696c23ba3cd964df59d743e070b84a5f81 # bigint-support

dev_dependencies:
  test: ^1.24.4
  lints: ^2.1.1
