name: znn_cli_dart
description: Zenon CLI tool
version: 0.0.4
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dcli: ^1.7.1
  znn_sdk_dart:
    git:
      url: https://github.com/zenon-network/znn_sdk_dart.git
      ref: 367ddc7fbfefb6484d7553d9ac7e4532003a7008 # v0.0.4

dev_dependencies:
  test: ^1.17.9
  lints: ^1.0.1
